/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package saxobank.home.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * BalancesMeCollateralCreditValue
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-20T19:24:00.374699022Z[GMT]")

public class BalancesMeCollateralCreditValue {
  @SerializedName("Line")
  private BigDecimal line = null;

  @SerializedName("UtilizationPct")
  private BigDecimal utilizationPct = null;

  @SerializedName("Exposure")
  private BigDecimal exposure = null;

  public BalancesMeCollateralCreditValue line(BigDecimal line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @Schema(description = "")
  public BigDecimal getLine() {
    return line;
  }

  public void setLine(BigDecimal line) {
    this.line = line;
  }

  public BalancesMeCollateralCreditValue utilizationPct(BigDecimal utilizationPct) {
    this.utilizationPct = utilizationPct;
    return this;
  }

   /**
   * Get utilizationPct
   * @return utilizationPct
  **/
  @Schema(description = "")
  public BigDecimal getUtilizationPct() {
    return utilizationPct;
  }

  public void setUtilizationPct(BigDecimal utilizationPct) {
    this.utilizationPct = utilizationPct;
  }

  public BalancesMeCollateralCreditValue exposure(BigDecimal exposure) {
    this.exposure = exposure;
    return this;
  }

   /**
   * Get exposure
   * @return exposure
  **/
  @Schema(description = "")
  public BigDecimal getExposure() {
    return exposure;
  }

  public void setExposure(BigDecimal exposure) {
    this.exposure = exposure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalancesMeCollateralCreditValue balancesMeCollateralCreditValue = (BalancesMeCollateralCreditValue) o;
    return Objects.equals(this.line, balancesMeCollateralCreditValue.line) &&
        Objects.equals(this.utilizationPct, balancesMeCollateralCreditValue.utilizationPct) &&
        Objects.equals(this.exposure, balancesMeCollateralCreditValue.exposure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line, utilizationPct, exposure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalancesMeCollateralCreditValue {\n");
    
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    utilizationPct: ").append(toIndentedString(utilizationPct)).append("\n");
    sb.append("    exposure: ").append(toIndentedString(exposure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
