/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package saxobank.home.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import saxobank.home.sdk.model.InstrumentsDetailsTickSizeSchemeElements;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * InstrumentsDetailsTickSizeScheme
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T18:24:56.181779897Z[GMT]")

public class InstrumentsDetailsTickSizeScheme {
  @SerializedName("DefaultTickSize")
  private BigDecimal defaultTickSize = null;

  @SerializedName("Elements")
  private List<InstrumentsDetailsTickSizeSchemeElements> elements = null;

  public InstrumentsDetailsTickSizeScheme defaultTickSize(BigDecimal defaultTickSize) {
    this.defaultTickSize = defaultTickSize;
    return this;
  }

   /**
   * Get defaultTickSize
   * @return defaultTickSize
  **/
  @Schema(description = "")
  public BigDecimal getDefaultTickSize() {
    return defaultTickSize;
  }

  public void setDefaultTickSize(BigDecimal defaultTickSize) {
    this.defaultTickSize = defaultTickSize;
  }

  public InstrumentsDetailsTickSizeScheme elements(List<InstrumentsDetailsTickSizeSchemeElements> elements) {
    this.elements = elements;
    return this;
  }

  public InstrumentsDetailsTickSizeScheme addElementsItem(InstrumentsDetailsTickSizeSchemeElements elementsItem) {
    if (this.elements == null) {
      this.elements = new ArrayList<InstrumentsDetailsTickSizeSchemeElements>();
    }
    this.elements.add(elementsItem);
    return this;
  }

   /**
   * Get elements
   * @return elements
  **/
  @Schema(description = "")
  public List<InstrumentsDetailsTickSizeSchemeElements> getElements() {
    return elements;
  }

  public void setElements(List<InstrumentsDetailsTickSizeSchemeElements> elements) {
    this.elements = elements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentsDetailsTickSizeScheme instrumentsDetailsTickSizeScheme = (InstrumentsDetailsTickSizeScheme) o;
    return Objects.equals(this.defaultTickSize, instrumentsDetailsTickSizeScheme.defaultTickSize) &&
        Objects.equals(this.elements, instrumentsDetailsTickSizeScheme.elements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultTickSize, elements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentsDetailsTickSizeScheme {\n");
    
    sb.append("    defaultTickSize: ").append(toIndentedString(defaultTickSize)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
