/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package saxobank.home.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InstrumentsDetailsFormat
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T18:24:56.181779897Z[GMT]")

public class InstrumentsDetailsFormat {
  @SerializedName("Decimals")
  private Long decimals = null;

  @SerializedName("OrderDecimals")
  private Long orderDecimals = null;

  public InstrumentsDetailsFormat decimals(Long decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * Get decimals
   * @return decimals
  **/
  @Schema(description = "")
  public Long getDecimals() {
    return decimals;
  }

  public void setDecimals(Long decimals) {
    this.decimals = decimals;
  }

  public InstrumentsDetailsFormat orderDecimals(Long orderDecimals) {
    this.orderDecimals = orderDecimals;
    return this;
  }

   /**
   * Get orderDecimals
   * @return orderDecimals
  **/
  @Schema(description = "")
  public Long getOrderDecimals() {
    return orderDecimals;
  }

  public void setOrderDecimals(Long orderDecimals) {
    this.orderDecimals = orderDecimals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentsDetailsFormat instrumentsDetailsFormat = (InstrumentsDetailsFormat) o;
    return Objects.equals(this.decimals, instrumentsDetailsFormat.decimals) &&
        Objects.equals(this.orderDecimals, instrumentsDetailsFormat.orderDecimals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(decimals, orderDecimals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentsDetailsFormat {\n");
    
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    orderDecimals: ").append(toIndentedString(orderDecimals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
