/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package saxobank.home.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * NetPositionsMePositionBase
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T17:11:38.297188217Z[GMT]")

public class NetPositionsMePositionBase {
  @SerializedName("AccountId")
  private String accountId = null;

  @SerializedName("AccountKey")
  private String accountKey = null;

  @SerializedName("Amount")
  private BigDecimal amount = null;

  @SerializedName("AssetType")
  private String assetType = null;

  @SerializedName("CanBeClosed")
  private Boolean canBeClosed = null;

  @SerializedName("ClientId")
  private String clientId = null;

  @SerializedName("CloseConversionRateSettled")
  private Boolean closeConversionRateSettled = null;

  @SerializedName("CorrelationKey")
  private String correlationKey = null;

  @SerializedName("ExecutionTimeOpen")
  private String executionTimeOpen = null;

  @SerializedName("IsForceOpen")
  private Boolean isForceOpen = null;

  @SerializedName("IsMarketOpen")
  private Boolean isMarketOpen = null;

  @SerializedName("LockedByBackOffice")
  private Boolean lockedByBackOffice = null;

  @SerializedName("OpenPrice")
  private BigDecimal openPrice = null;

  @SerializedName("OpenPriceIncludingCosts")
  private BigDecimal openPriceIncludingCosts = null;

  @SerializedName("SourceOrderId")
  private String sourceOrderId = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("Uic")
  private Long uic = null;

  @SerializedName("ValueDate")
  private String valueDate = null;

  public NetPositionsMePositionBase accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @Schema(description = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public NetPositionsMePositionBase accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

   /**
   * Get accountKey
   * @return accountKey
  **/
  @Schema(description = "")
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }

  public NetPositionsMePositionBase amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public NetPositionsMePositionBase assetType(String assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @Schema(description = "")
  public String getAssetType() {
    return assetType;
  }

  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }

  public NetPositionsMePositionBase canBeClosed(Boolean canBeClosed) {
    this.canBeClosed = canBeClosed;
    return this;
  }

   /**
   * Get canBeClosed
   * @return canBeClosed
  **/
  @Schema(description = "")
  public Boolean isCanBeClosed() {
    return canBeClosed;
  }

  public void setCanBeClosed(Boolean canBeClosed) {
    this.canBeClosed = canBeClosed;
  }

  public NetPositionsMePositionBase clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @Schema(description = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public NetPositionsMePositionBase closeConversionRateSettled(Boolean closeConversionRateSettled) {
    this.closeConversionRateSettled = closeConversionRateSettled;
    return this;
  }

   /**
   * Get closeConversionRateSettled
   * @return closeConversionRateSettled
  **/
  @Schema(description = "")
  public Boolean isCloseConversionRateSettled() {
    return closeConversionRateSettled;
  }

  public void setCloseConversionRateSettled(Boolean closeConversionRateSettled) {
    this.closeConversionRateSettled = closeConversionRateSettled;
  }

  public NetPositionsMePositionBase correlationKey(String correlationKey) {
    this.correlationKey = correlationKey;
    return this;
  }

   /**
   * Get correlationKey
   * @return correlationKey
  **/
  @Schema(description = "")
  public String getCorrelationKey() {
    return correlationKey;
  }

  public void setCorrelationKey(String correlationKey) {
    this.correlationKey = correlationKey;
  }

  public NetPositionsMePositionBase executionTimeOpen(String executionTimeOpen) {
    this.executionTimeOpen = executionTimeOpen;
    return this;
  }

   /**
   * Get executionTimeOpen
   * @return executionTimeOpen
  **/
  @Schema(description = "")
  public String getExecutionTimeOpen() {
    return executionTimeOpen;
  }

  public void setExecutionTimeOpen(String executionTimeOpen) {
    this.executionTimeOpen = executionTimeOpen;
  }

  public NetPositionsMePositionBase isForceOpen(Boolean isForceOpen) {
    this.isForceOpen = isForceOpen;
    return this;
  }

   /**
   * Get isForceOpen
   * @return isForceOpen
  **/
  @Schema(description = "")
  public Boolean isIsForceOpen() {
    return isForceOpen;
  }

  public void setIsForceOpen(Boolean isForceOpen) {
    this.isForceOpen = isForceOpen;
  }

  public NetPositionsMePositionBase isMarketOpen(Boolean isMarketOpen) {
    this.isMarketOpen = isMarketOpen;
    return this;
  }

   /**
   * Get isMarketOpen
   * @return isMarketOpen
  **/
  @Schema(description = "")
  public Boolean isIsMarketOpen() {
    return isMarketOpen;
  }

  public void setIsMarketOpen(Boolean isMarketOpen) {
    this.isMarketOpen = isMarketOpen;
  }

  public NetPositionsMePositionBase lockedByBackOffice(Boolean lockedByBackOffice) {
    this.lockedByBackOffice = lockedByBackOffice;
    return this;
  }

   /**
   * Get lockedByBackOffice
   * @return lockedByBackOffice
  **/
  @Schema(description = "")
  public Boolean isLockedByBackOffice() {
    return lockedByBackOffice;
  }

  public void setLockedByBackOffice(Boolean lockedByBackOffice) {
    this.lockedByBackOffice = lockedByBackOffice;
  }

  public NetPositionsMePositionBase openPrice(BigDecimal openPrice) {
    this.openPrice = openPrice;
    return this;
  }

   /**
   * Get openPrice
   * @return openPrice
  **/
  @Schema(description = "")
  public BigDecimal getOpenPrice() {
    return openPrice;
  }

  public void setOpenPrice(BigDecimal openPrice) {
    this.openPrice = openPrice;
  }

  public NetPositionsMePositionBase openPriceIncludingCosts(BigDecimal openPriceIncludingCosts) {
    this.openPriceIncludingCosts = openPriceIncludingCosts;
    return this;
  }

   /**
   * Get openPriceIncludingCosts
   * @return openPriceIncludingCosts
  **/
  @Schema(description = "")
  public BigDecimal getOpenPriceIncludingCosts() {
    return openPriceIncludingCosts;
  }

  public void setOpenPriceIncludingCosts(BigDecimal openPriceIncludingCosts) {
    this.openPriceIncludingCosts = openPriceIncludingCosts;
  }

  public NetPositionsMePositionBase sourceOrderId(String sourceOrderId) {
    this.sourceOrderId = sourceOrderId;
    return this;
  }

   /**
   * Get sourceOrderId
   * @return sourceOrderId
  **/
  @Schema(description = "")
  public String getSourceOrderId() {
    return sourceOrderId;
  }

  public void setSourceOrderId(String sourceOrderId) {
    this.sourceOrderId = sourceOrderId;
  }

  public NetPositionsMePositionBase status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public NetPositionsMePositionBase uic(Long uic) {
    this.uic = uic;
    return this;
  }

   /**
   * Get uic
   * @return uic
  **/
  @Schema(description = "")
  public Long getUic() {
    return uic;
  }

  public void setUic(Long uic) {
    this.uic = uic;
  }

  public NetPositionsMePositionBase valueDate(String valueDate) {
    this.valueDate = valueDate;
    return this;
  }

   /**
   * Get valueDate
   * @return valueDate
  **/
  @Schema(description = "")
  public String getValueDate() {
    return valueDate;
  }

  public void setValueDate(String valueDate) {
    this.valueDate = valueDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetPositionsMePositionBase netPositionsMePositionBase = (NetPositionsMePositionBase) o;
    return Objects.equals(this.accountId, netPositionsMePositionBase.accountId) &&
        Objects.equals(this.accountKey, netPositionsMePositionBase.accountKey) &&
        Objects.equals(this.amount, netPositionsMePositionBase.amount) &&
        Objects.equals(this.assetType, netPositionsMePositionBase.assetType) &&
        Objects.equals(this.canBeClosed, netPositionsMePositionBase.canBeClosed) &&
        Objects.equals(this.clientId, netPositionsMePositionBase.clientId) &&
        Objects.equals(this.closeConversionRateSettled, netPositionsMePositionBase.closeConversionRateSettled) &&
        Objects.equals(this.correlationKey, netPositionsMePositionBase.correlationKey) &&
        Objects.equals(this.executionTimeOpen, netPositionsMePositionBase.executionTimeOpen) &&
        Objects.equals(this.isForceOpen, netPositionsMePositionBase.isForceOpen) &&
        Objects.equals(this.isMarketOpen, netPositionsMePositionBase.isMarketOpen) &&
        Objects.equals(this.lockedByBackOffice, netPositionsMePositionBase.lockedByBackOffice) &&
        Objects.equals(this.openPrice, netPositionsMePositionBase.openPrice) &&
        Objects.equals(this.openPriceIncludingCosts, netPositionsMePositionBase.openPriceIncludingCosts) &&
        Objects.equals(this.sourceOrderId, netPositionsMePositionBase.sourceOrderId) &&
        Objects.equals(this.status, netPositionsMePositionBase.status) &&
        Objects.equals(this.uic, netPositionsMePositionBase.uic) &&
        Objects.equals(this.valueDate, netPositionsMePositionBase.valueDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountKey, amount, assetType, canBeClosed, clientId, closeConversionRateSettled, correlationKey, executionTimeOpen, isForceOpen, isMarketOpen, lockedByBackOffice, openPrice, openPriceIncludingCosts, sourceOrderId, status, uic, valueDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetPositionsMePositionBase {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    canBeClosed: ").append(toIndentedString(canBeClosed)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    closeConversionRateSettled: ").append(toIndentedString(closeConversionRateSettled)).append("\n");
    sb.append("    correlationKey: ").append(toIndentedString(correlationKey)).append("\n");
    sb.append("    executionTimeOpen: ").append(toIndentedString(executionTimeOpen)).append("\n");
    sb.append("    isForceOpen: ").append(toIndentedString(isForceOpen)).append("\n");
    sb.append("    isMarketOpen: ").append(toIndentedString(isMarketOpen)).append("\n");
    sb.append("    lockedByBackOffice: ").append(toIndentedString(lockedByBackOffice)).append("\n");
    sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
    sb.append("    openPriceIncludingCosts: ").append(toIndentedString(openPriceIncludingCosts)).append("\n");
    sb.append("    sourceOrderId: ").append(toIndentedString(sourceOrderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uic: ").append(toIndentedString(uic)).append("\n");
    sb.append("    valueDate: ").append(toIndentedString(valueDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
