/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package saxobank.home.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import saxobank.home.sdk.model.NetPositionsMeNetPositionBase;
import saxobank.home.sdk.model.NetPositionsMeNetPositionView;

import java.io.IOException;
/**
 * NetPositionsMeData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T18:24:56.181779897Z[GMT]")

public class NetPositionsMeData {
  @SerializedName("NetPositionBase")
  private NetPositionsMeNetPositionBase netPositionBase = null;

  @SerializedName("NetPositionId")
  private String netPositionId = null;

  @SerializedName("NetPositionView")
  private NetPositionsMeNetPositionView netPositionView = null;

  public NetPositionsMeData netPositionBase(NetPositionsMeNetPositionBase netPositionBase) {
    this.netPositionBase = netPositionBase;
    return this;
  }

   /**
   * Get netPositionBase
   * @return netPositionBase
  **/
  @Schema(description = "")
  public NetPositionsMeNetPositionBase getNetPositionBase() {
    return netPositionBase;
  }

  public void setNetPositionBase(NetPositionsMeNetPositionBase netPositionBase) {
    this.netPositionBase = netPositionBase;
  }

  public NetPositionsMeData netPositionId(String netPositionId) {
    this.netPositionId = netPositionId;
    return this;
  }

   /**
   * Get netPositionId
   * @return netPositionId
  **/
  @Schema(description = "")
  public String getNetPositionId() {
    return netPositionId;
  }

  public void setNetPositionId(String netPositionId) {
    this.netPositionId = netPositionId;
  }

  public NetPositionsMeData netPositionView(NetPositionsMeNetPositionView netPositionView) {
    this.netPositionView = netPositionView;
    return this;
  }

   /**
   * Get netPositionView
   * @return netPositionView
  **/
  @Schema(description = "")
  public NetPositionsMeNetPositionView getNetPositionView() {
    return netPositionView;
  }

  public void setNetPositionView(NetPositionsMeNetPositionView netPositionView) {
    this.netPositionView = netPositionView;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetPositionsMeData netPositionsMeData = (NetPositionsMeData) o;
    return Objects.equals(this.netPositionBase, netPositionsMeData.netPositionBase) &&
        Objects.equals(this.netPositionId, netPositionsMeData.netPositionId) &&
        Objects.equals(this.netPositionView, netPositionsMeData.netPositionView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(netPositionBase, netPositionId, netPositionView);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetPositionsMeData {\n");
    
    sb.append("    netPositionBase: ").append(toIndentedString(netPositionBase)).append("\n");
    sb.append("    netPositionId: ").append(toIndentedString(netPositionId)).append("\n");
    sb.append("    netPositionView: ").append(toIndentedString(netPositionView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
