/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * InstrumentsDetailsIpoDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-20T19:53:46.685908542Z[GMT]")

public class InstrumentsDetailsIpoDetails {
  @SerializedName("MaxLeveragePct")
  private BigDecimal maxLeveragePct = null;

  @SerializedName("MaxLotSize")
  private BigDecimal maxLotSize = null;

  public InstrumentsDetailsIpoDetails maxLeveragePct(BigDecimal maxLeveragePct) {
    this.maxLeveragePct = maxLeveragePct;
    return this;
  }

   /**
   * Get maxLeveragePct
   * @return maxLeveragePct
  **/
  @Schema(description = "")
  public BigDecimal getMaxLeveragePct() {
    return maxLeveragePct;
  }

  public void setMaxLeveragePct(BigDecimal maxLeveragePct) {
    this.maxLeveragePct = maxLeveragePct;
  }

  public InstrumentsDetailsIpoDetails maxLotSize(BigDecimal maxLotSize) {
    this.maxLotSize = maxLotSize;
    return this;
  }

   /**
   * Get maxLotSize
   * @return maxLotSize
  **/
  @Schema(description = "")
  public BigDecimal getMaxLotSize() {
    return maxLotSize;
  }

  public void setMaxLotSize(BigDecimal maxLotSize) {
    this.maxLotSize = maxLotSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentsDetailsIpoDetails instrumentsDetailsIpoDetails = (InstrumentsDetailsIpoDetails) o;
    return Objects.equals(this.maxLeveragePct, instrumentsDetailsIpoDetails.maxLeveragePct) &&
        Objects.equals(this.maxLotSize, instrumentsDetailsIpoDetails.maxLotSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxLeveragePct, maxLotSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentsDetailsIpoDetails {\n");
    
    sb.append("    maxLeveragePct: ").append(toIndentedString(maxLeveragePct)).append("\n");
    sb.append("    maxLotSize: ").append(toIndentedString(maxLotSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
