/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NetPositionsMeData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * NetPositionsMe
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T18:24:56.181779897Z[GMT]")

public class NetPositionsMe {
  @SerializedName("__count")
  private Integer _count = null;

  @SerializedName("Data")
  private List<NetPositionsMeData> data = null;

  public NetPositionsMe _count(Integer _count) {
    this._count = _count;
    return this;
  }

   /**
   * Get _count
   * @return _count
  **/
  @Schema(description = "")
  public Integer getCount() {
    return _count;
  }

  public void setCount(Integer _count) {
    this._count = _count;
  }

  public NetPositionsMe data(List<NetPositionsMeData> data) {
    this.data = data;
    return this;
  }

  public NetPositionsMe addDataItem(NetPositionsMeData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<NetPositionsMeData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<NetPositionsMeData> getData() {
    return data;
  }

  public void setData(List<NetPositionsMeData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetPositionsMe netPositionsMe = (NetPositionsMe) o;
    return Objects.equals(this._count, netPositionsMe._count) &&
        Objects.equals(this.data, netPositionsMe.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_count, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetPositionsMe {\n");
    
    sb.append("    _count: ").append(toIndentedString(_count)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
