/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Openapitradev2ordersOrderDuration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Openapitradev2ordersOrders
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T18:24:56.181779897Z[GMT]")

public class Openapitradev2ordersOrders {
  @SerializedName("AccountKey")
  private String accountKey = null;

  @SerializedName("AffiliateInfoRequired")
  private String affiliateInfoRequired = null;

  @SerializedName("Amount")
  private BigDecimal amount = null;

  @SerializedName("AssetType")
  private String assetType = null;

  @SerializedName("BuySell")
  private String buySell = null;

  @SerializedName("ManualOrder")
  private Boolean manualOrder = null;

  @SerializedName("OrderDuration")
  private Openapitradev2ordersOrderDuration orderDuration = null;

  @SerializedName("OrderPrice")
  private BigDecimal orderPrice = null;

  @SerializedName("OrderType")
  private String orderType = null;

  @SerializedName("Uic")
  private Long uic = null;

  public Openapitradev2ordersOrders accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

   /**
   * Get accountKey
   * @return accountKey
  **/
  @Schema(description = "")
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }

  public Openapitradev2ordersOrders affiliateInfoRequired(String affiliateInfoRequired) {
    this.affiliateInfoRequired = affiliateInfoRequired;
    return this;
  }

   /**
   * Get affiliateInfoRequired
   * @return affiliateInfoRequired
  **/
  @Schema(description = "")
  public String getAffiliateInfoRequired() {
    return affiliateInfoRequired;
  }

  public void setAffiliateInfoRequired(String affiliateInfoRequired) {
    this.affiliateInfoRequired = affiliateInfoRequired;
  }

  public Openapitradev2ordersOrders amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public Openapitradev2ordersOrders assetType(String assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @Schema(description = "")
  public String getAssetType() {
    return assetType;
  }

  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }

  public Openapitradev2ordersOrders buySell(String buySell) {
    this.buySell = buySell;
    return this;
  }

   /**
   * Get buySell
   * @return buySell
  **/
  @Schema(description = "")
  public String getBuySell() {
    return buySell;
  }

  public void setBuySell(String buySell) {
    this.buySell = buySell;
  }

  public Openapitradev2ordersOrders manualOrder(Boolean manualOrder) {
    this.manualOrder = manualOrder;
    return this;
  }

   /**
   * Get manualOrder
   * @return manualOrder
  **/
  @Schema(description = "")
  public Boolean isManualOrder() {
    return manualOrder;
  }

  public void setManualOrder(Boolean manualOrder) {
    this.manualOrder = manualOrder;
  }

  public Openapitradev2ordersOrders orderDuration(Openapitradev2ordersOrderDuration orderDuration) {
    this.orderDuration = orderDuration;
    return this;
  }

   /**
   * Get orderDuration
   * @return orderDuration
  **/
  @Schema(description = "")
  public Openapitradev2ordersOrderDuration getOrderDuration() {
    return orderDuration;
  }

  public void setOrderDuration(Openapitradev2ordersOrderDuration orderDuration) {
    this.orderDuration = orderDuration;
  }

  public Openapitradev2ordersOrders orderPrice(BigDecimal orderPrice) {
    this.orderPrice = orderPrice;
    return this;
  }

   /**
   * Get orderPrice
   * @return orderPrice
  **/
  @Schema(description = "")
  public BigDecimal getOrderPrice() {
    return orderPrice;
  }

  public void setOrderPrice(BigDecimal orderPrice) {
    this.orderPrice = orderPrice;
  }

  public Openapitradev2ordersOrders orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @Schema(description = "")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public Openapitradev2ordersOrders uic(Long uic) {
    this.uic = uic;
    return this;
  }

   /**
   * Get uic
   * @return uic
  **/
  @Schema(description = "")
  public Long getUic() {
    return uic;
  }

  public void setUic(Long uic) {
    this.uic = uic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Openapitradev2ordersOrders openapitradev2ordersOrders = (Openapitradev2ordersOrders) o;
    return Objects.equals(this.accountKey, openapitradev2ordersOrders.accountKey) &&
        Objects.equals(this.affiliateInfoRequired, openapitradev2ordersOrders.affiliateInfoRequired) &&
        Objects.equals(this.amount, openapitradev2ordersOrders.amount) &&
        Objects.equals(this.assetType, openapitradev2ordersOrders.assetType) &&
        Objects.equals(this.buySell, openapitradev2ordersOrders.buySell) &&
        Objects.equals(this.manualOrder, openapitradev2ordersOrders.manualOrder) &&
        Objects.equals(this.orderDuration, openapitradev2ordersOrders.orderDuration) &&
        Objects.equals(this.orderPrice, openapitradev2ordersOrders.orderPrice) &&
        Objects.equals(this.orderType, openapitradev2ordersOrders.orderType) &&
        Objects.equals(this.uic, openapitradev2ordersOrders.uic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountKey, affiliateInfoRequired, amount, assetType, buySell, manualOrder, orderDuration, orderPrice, orderType, uic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Openapitradev2ordersOrders {\n");
    
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("    affiliateInfoRequired: ").append(toIndentedString(affiliateInfoRequired)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    buySell: ").append(toIndentedString(buySell)).append("\n");
    sb.append("    manualOrder: ").append(toIndentedString(manualOrder)).append("\n");
    sb.append("    orderDuration: ").append(toIndentedString(orderDuration)).append("\n");
    sb.append("    orderPrice: ").append(toIndentedString(orderPrice)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    uic: ").append(toIndentedString(uic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
