/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OrderActivitiesData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OrderActivities
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-27T21:00:40.494761882Z[GMT]")

public class OrderActivities {
  @SerializedName("__count")
  private Long _count = null;

  @SerializedName("__nextPoll")
  private String _nextPoll = null;

  @SerializedName("Data")
  private List<OrderActivitiesData> data = null;

  public OrderActivities _count(Long _count) {
    this._count = _count;
    return this;
  }

   /**
   * Get _count
   * @return _count
  **/
  @Schema(description = "")
  public Long getCount() {
    return _count;
  }

  public void setCount(Long _count) {
    this._count = _count;
  }

  public OrderActivities _nextPoll(String _nextPoll) {
    this._nextPoll = _nextPoll;
    return this;
  }

   /**
   * Get _nextPoll
   * @return _nextPoll
  **/
  @Schema(description = "")
  public String getNextPoll() {
    return _nextPoll;
  }

  public void setNextPoll(String _nextPoll) {
    this._nextPoll = _nextPoll;
  }

  public OrderActivities data(List<OrderActivitiesData> data) {
    this.data = data;
    return this;
  }

  public OrderActivities addDataItem(OrderActivitiesData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<OrderActivitiesData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<OrderActivitiesData> getData() {
    return data;
  }

  public void setData(List<OrderActivitiesData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderActivities orderActivities = (OrderActivities) o;
    return Objects.equals(this._count, orderActivities._count) &&
        Objects.equals(this._nextPoll, orderActivities._nextPoll) &&
        Objects.equals(this.data, orderActivities.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_count, _nextPoll, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderActivities {\n");
    
    sb.append("    _count: ").append(toIndentedString(_count)).append("\n");
    sb.append("    _nextPoll: ").append(toIndentedString(_nextPoll)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
