/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * UsersMe
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-20T19:53:46.685908542Z[GMT]")

public class UsersMe {
  @SerializedName("Active")
  private Boolean active = null;

  @SerializedName("ClientKey")
  private String clientKey = null;

  @SerializedName("Culture")
  private String culture = null;

  @SerializedName("Language")
  private String language = null;

  @SerializedName("LastLoginStatus")
  private String lastLoginStatus = null;

  @SerializedName("LastLoginTime")
  private String lastLoginTime = null;

  @SerializedName("LegalAssetTypes")
  private List<String> legalAssetTypes = null;

  @SerializedName("MarketDataViaOpenApiTermsAccepted")
  private Boolean marketDataViaOpenApiTermsAccepted = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("TimeZoneId")
  private Long timeZoneId = null;

  @SerializedName("UserId")
  private String userId = null;

  @SerializedName("UserKey")
  private String userKey = null;

  public UsersMe active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public UsersMe clientKey(String clientKey) {
    this.clientKey = clientKey;
    return this;
  }

   /**
   * Get clientKey
   * @return clientKey
  **/
  @Schema(description = "")
  public String getClientKey() {
    return clientKey;
  }

  public void setClientKey(String clientKey) {
    this.clientKey = clientKey;
  }

  public UsersMe culture(String culture) {
    this.culture = culture;
    return this;
  }

   /**
   * Get culture
   * @return culture
  **/
  @Schema(description = "")
  public String getCulture() {
    return culture;
  }

  public void setCulture(String culture) {
    this.culture = culture;
  }

  public UsersMe language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public UsersMe lastLoginStatus(String lastLoginStatus) {
    this.lastLoginStatus = lastLoginStatus;
    return this;
  }

   /**
   * Get lastLoginStatus
   * @return lastLoginStatus
  **/
  @Schema(description = "")
  public String getLastLoginStatus() {
    return lastLoginStatus;
  }

  public void setLastLoginStatus(String lastLoginStatus) {
    this.lastLoginStatus = lastLoginStatus;
  }

  public UsersMe lastLoginTime(String lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
    return this;
  }

   /**
   * Get lastLoginTime
   * @return lastLoginTime
  **/
  @Schema(description = "")
  public String getLastLoginTime() {
    return lastLoginTime;
  }

  public void setLastLoginTime(String lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
  }

  public UsersMe legalAssetTypes(List<String> legalAssetTypes) {
    this.legalAssetTypes = legalAssetTypes;
    return this;
  }

  public UsersMe addLegalAssetTypesItem(String legalAssetTypesItem) {
    if (this.legalAssetTypes == null) {
      this.legalAssetTypes = new ArrayList<String>();
    }
    this.legalAssetTypes.add(legalAssetTypesItem);
    return this;
  }

   /**
   * Get legalAssetTypes
   * @return legalAssetTypes
  **/
  @Schema(description = "")
  public List<String> getLegalAssetTypes() {
    return legalAssetTypes;
  }

  public void setLegalAssetTypes(List<String> legalAssetTypes) {
    this.legalAssetTypes = legalAssetTypes;
  }

  public UsersMe marketDataViaOpenApiTermsAccepted(Boolean marketDataViaOpenApiTermsAccepted) {
    this.marketDataViaOpenApiTermsAccepted = marketDataViaOpenApiTermsAccepted;
    return this;
  }

   /**
   * Get marketDataViaOpenApiTermsAccepted
   * @return marketDataViaOpenApiTermsAccepted
  **/
  @Schema(description = "")
  public Boolean isMarketDataViaOpenApiTermsAccepted() {
    return marketDataViaOpenApiTermsAccepted;
  }

  public void setMarketDataViaOpenApiTermsAccepted(Boolean marketDataViaOpenApiTermsAccepted) {
    this.marketDataViaOpenApiTermsAccepted = marketDataViaOpenApiTermsAccepted;
  }

  public UsersMe name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UsersMe timeZoneId(Long timeZoneId) {
    this.timeZoneId = timeZoneId;
    return this;
  }

   /**
   * Get timeZoneId
   * @return timeZoneId
  **/
  @Schema(description = "")
  public Long getTimeZoneId() {
    return timeZoneId;
  }

  public void setTimeZoneId(Long timeZoneId) {
    this.timeZoneId = timeZoneId;
  }

  public UsersMe userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public UsersMe userKey(String userKey) {
    this.userKey = userKey;
    return this;
  }

   /**
   * Get userKey
   * @return userKey
  **/
  @Schema(description = "")
  public String getUserKey() {
    return userKey;
  }

  public void setUserKey(String userKey) {
    this.userKey = userKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersMe usersMe = (UsersMe) o;
    return Objects.equals(this.active, usersMe.active) &&
        Objects.equals(this.clientKey, usersMe.clientKey) &&
        Objects.equals(this.culture, usersMe.culture) &&
        Objects.equals(this.language, usersMe.language) &&
        Objects.equals(this.lastLoginStatus, usersMe.lastLoginStatus) &&
        Objects.equals(this.lastLoginTime, usersMe.lastLoginTime) &&
        Objects.equals(this.legalAssetTypes, usersMe.legalAssetTypes) &&
        Objects.equals(this.marketDataViaOpenApiTermsAccepted, usersMe.marketDataViaOpenApiTermsAccepted) &&
        Objects.equals(this.name, usersMe.name) &&
        Objects.equals(this.timeZoneId, usersMe.timeZoneId) &&
        Objects.equals(this.userId, usersMe.userId) &&
        Objects.equals(this.userKey, usersMe.userKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, clientKey, culture, language, lastLoginStatus, lastLoginTime, legalAssetTypes, marketDataViaOpenApiTermsAccepted, name, timeZoneId, userId, userKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersMe {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    clientKey: ").append(toIndentedString(clientKey)).append("\n");
    sb.append("    culture: ").append(toIndentedString(culture)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lastLoginStatus: ").append(toIndentedString(lastLoginStatus)).append("\n");
    sb.append("    lastLoginTime: ").append(toIndentedString(lastLoginTime)).append("\n");
    sb.append("    legalAssetTypes: ").append(toIndentedString(legalAssetTypes)).append("\n");
    sb.append("    marketDataViaOpenApiTermsAccepted: ").append(toIndentedString(marketDataViaOpenApiTermsAccepted)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timeZoneId: ").append(toIndentedString(timeZoneId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userKey: ").append(toIndentedString(userKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
