/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Openapitradev2ordersOrderDuration1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V2OrdersBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-27T21:00:40.494761882Z[GMT]")

public class V2OrdersBody1 {
  @SerializedName("OrderType")
  private String orderType = null;

  @SerializedName("OrderDuration")
  private Openapitradev2ordersOrderDuration1 orderDuration = null;

  @SerializedName("AccountKey")
  private String accountKey = null;

  public V2OrdersBody1 orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * The Order Type. See https://www.developer.saxo/openapi/referencedocs/trade/v2/orders/changeorder/9304f171cf009b860f398733b4ae32ef/placeableordertype/1434dd641953bb711e8c6d3f7ad963e7
   * @return orderType
  **/
  @Schema(description = "The Order Type. See https://www.developer.saxo/openapi/referencedocs/trade/v2/orders/changeorder/9304f171cf009b860f398733b4ae32ef/placeableordertype/1434dd641953bb711e8c6d3f7ad963e7")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public V2OrdersBody1 orderDuration(Openapitradev2ordersOrderDuration1 orderDuration) {
    this.orderDuration = orderDuration;
    return this;
  }

   /**
   * Get orderDuration
   * @return orderDuration
  **/
  @Schema(description = "")
  public Openapitradev2ordersOrderDuration1 getOrderDuration() {
    return orderDuration;
  }

  public void setOrderDuration(Openapitradev2ordersOrderDuration1 orderDuration) {
    this.orderDuration = orderDuration;
  }

  public V2OrdersBody1 accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

   /**
   * Unique key identifying the account.
   * @return accountKey
  **/
  @Schema(description = "Unique key identifying the account.")
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2OrdersBody1 v2OrdersBody1 = (V2OrdersBody1) o;
    return Objects.equals(this.orderType, v2OrdersBody1.orderType) &&
        Objects.equals(this.orderDuration, v2OrdersBody1.orderDuration) &&
        Objects.equals(this.accountKey, v2OrdersBody1.accountKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderType, orderDuration, accountKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2OrdersBody1 {\n");
    
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    orderDuration: ").append(toIndentedString(orderDuration)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
