/*
 * Saxobank trading API
 * Saxobank trading API
 *
 * OpenAPI spec version: 0.1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;

import saxobank.home.sdk.api.AuthClientApi;
import saxobank.home.sdk.model.AuthData;

import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AuthClientApi
 */
@Ignore
public class AuthClientApiTest {

    private final AuthClientApi api = new AuthClientApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void authdataGetTest() throws Exception {
        AuthData response = api.authdataGet();

        // TODO: test validations
    }
}
